apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitverse-nft-bot-deployment
  labels:
    app: bitverse-nft-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitverse-nft-bot
  template:
    metadata:
      labels:
        app: bitverse-nft-bot
    spec:
      containers:
      - name: bitverse-nft-bot 
        image: registry.digitalocean.com/deadloct/bitverse-nft-bot:latest
        env:
        - name: BITVERSE_NFT_BOT_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
                name: bitverse-nft-bot-secrets
                key: BITVERSE_NFT_BOT_AUTH_TOKEN
